### ISSUE TITLE
Move files from old google drive to new one: Glen

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#14]
### Overview
We need to move our files to a Google shared drive from the Google shared folder.

### Action Items
- [x] move the files that are owned by you

### Resources/Instructions
**Glen's files**
![glen google image](https://user-images.githubusercontent.com/37763229/125212146-40fd1e00-e260-11eb-9bd3-d7b56ae00103.PNG)
Move the files from the [old folder](https://drive.google.com/drive/folders/1i_mjlTp0tNfUiXeXN4YmbbuJg6iF-hPz) to the [new folder](https://drive.google.com/drive/folders/1dmX5df5TXm8F209O4-_BRmuW0NIcT-Ss)

**Instructions**
1. Select the three files in the old folder
2. Right click on them and select Move
3. then a dialog box will come up and you hit the arrow that points left, until you get to a choice for "Shared Drives >"
4. Choose the Shared Drives
5. Then Choose the one marked "Hack for LA Org Admin" 
6. Then choose the folder inside of it called "Hack for LA Org Admin"
7. Then choose the folder inside of it called "Recordings"
8. Then click the Select or Move button (I can't remember what it is called)

**Comment by glenflorendo** [comment]
This is all done!

Note: I did get this error `Folders can't be moved to shared drives yet`, so I just recreated the folders in the shared drive and just moved the files themselves. From my quick search, this looks to be an permissions issue.
