### ISSUE TITLE
Move files from old google drive to new one: Karen

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#15]
### Overview
We need to move our files to a Google shared drive from the Google shared folder.

### Action Items
- [x]  move the files that are owned by you

### Resources/Instructions

**Karen's files**
![karen google image](https://user-images.githubusercontent.com/37763229/125212102-f11e5700-e25f-11eb-9fb8-9632c18efdcb.PNG)
Move the files from the [old folder](https://drive.google.com/drive/folders/1ZFgHP1qCkRC6IjbMnVpzvpSg-QV1GRdi) to the [new folder](https://drive.google.com/drive/folders/13aT7T3HblNidcwm2CMy7LQg-mAULL3Q7)

**Instructions**
1. Select the two files in the old folder
2. Right click on them and select Move
3. then a dialog box will come up and you hit the arrow that points left, until you get to a choice for "Shared Drives >"
4. Choose the Shared Drives
5. Then Choose the one marked "Hack for LA Org Admin" 
6. Then choose the folder inside of it called "Hack for LA Org Admin"
7. Then choose the folder inside of it called "Admin Guides"
8. Then click the Select or Move button (I can't remember what it is called)

**Comment by kcoronel** [comment]
Done on 7/14
