### ISSUE TITLE
You need to turn on 2FA on your GitHub ASAP (we are making it mandatory at HfLA)

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#45]
### Overview
We are turning on 2-Factor Authentication (2FA) required on Hack for LA's GitHub.  Anyone who has not turned on 2FA will be removed automatically by GitHub when we do it.  Then you have to ask to be re added to all the repos you had before, and it will be a total PIA.

### Action Items
- If your GitHub handle is on the list below, it means you have been an active member of our GitHub in the last 3 months.
   - Go to this [slide deck](https://docs.google.com/presentation/d/1CVxhSjUbElQx83ZCrWBTBiz7qW7wmydPc99gJLmvejQ/preview) and follow the instructions to turn on 2FA
- If you are a Product Manager
  - Go through your roster of active members and see who is affected and write to them (slack, email, texts, whatever it takes).

### People affected by this
@GTOnizuka13
@Excursionpreneur
@ampers-and
@TicoGitHubII
@eq2thex
@jedimil
@jonarcisse
@philippe101
@nicoleiocana
@ShikaZzz
@DongYoon-tech
@mrtmrt233
@mitrab108
@cuevaskoch
@Charity59
@PLoiya
@kande81
@kmw
@nickelworks
@umairmoinuddin
@ChristyCakes
@hiran11
@ebele-oputa
@minar68
@sugarsyntax
@ugujral
@jx114
@jyron
@pedro218
@DanielDev200
@gregboyer
@pnguye17
@TracyLuu
@joanna-pham
@mehmehmehlol
@elpen84
@acontreras77
@BethBethBeth
@elizabethhonest
@clairemoorecantwell
@kellychoe
@chiusano
@LIlinit
@dradamski
@fourmatte
@patrickm-tan
@ialv44
@Oluwafemi-Jegede
@K2kshitij
@delphinevendryes
@martyboggs
@EchoProject
@rajindermavi
@NavratiK
@patula006
@linndaqun
@kkchu791
@legendarycoder1004
@IpshitaSingh
@shebacodes
@gr4ssman
@joshuakong818
@asselabilova
@vishrut-goel
@barbaralaw
@TugbaMet
@dannygarcia193
@glsonline
@steve-cahn
@Peter-Nooteboom
@enosV
@athya
@engmaggi
@brandonjturner
@summerharveyux
@miolow
@gjreig
@katelyntn
@MalakH21
@mrao2
@iamtreetop
@BryonPm
@Honrao-Akshata
@lindamejia
@Carter-tc
@nanoarzqta
@Aparna1Gopal
@angle-zhang
@erikguntner
@Vallsurf
@josiehandeveloper
@qooqu
@melissamurphy
@elyselam
@baipai
@fancyham
@webdevangelie
@ryanhkim997
@lemazza
@corwinstephen
@tan-zhou
@hotafrosauce1
@akhaleghi
@CJimenez-O
@jun-snow
@imanuelcg
@hinalsj
@markmatney
@greg-dixon
@ldaws003
@sidiknatasha
@brandohayes
@Abel-Zambrano
@aatain
@Kazuki0131
@hisergiorojas
@vadzimk
@ashleylin1
@grhhhh
@funbunch
@hamazumi
@maxskewes
@zhao-li-github
@HackforLABot
@Evon081
@Jain8888
@kevindphan
@KristenDLR
@navarroliuanthony
@TeddyTelanoff
@taylorwagner
@ShrutiMukherjee
@JackieRiley1
@DGnzl
@sdimran
@mcmorgan27
@qaz6209031
@miguel-hugo
@Ambmoney
@amnak1284
@naomiec
@tamalatrinh
@vbopardi
@justin1j
@RyanCahela
@dking1342
@mmaecruz
@royceduong
@Safox1
@coderlore

### Why can't things just stay as they are?
I wish there was another way to handle this, but sadly there is not :sob:  Our onboarding process has become cumbersome and slow because we spend so much time checking 2FA.  Starting the week after, I will lose the onboarding team and be trying to handle it solo.  It's hard enough to help everyone, without also having to repeatedly manually check people's 2FA status.  Thanks for your understanding

**Comment by kcoronel** [comment]
Today, Bonnie messaged each Hack for LA project team by going through the [hackforla.org project page](https://www.hackforla.org/projects/)

**Comment by GigiUxR** [comment]
Hi

I did this and received confirmation for it. Is it not showing up?

**Comment by fancyham** [comment]
Hi @ExperimentsInHonesty, could I be re-added?  I got bumped off!
