### ISSUE TITLE
2023 Meetup set up

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#51]
### Overview
We need to set up all the meetups for 2023 including the zoom webinar links

### Action Items
- [x] Add dates the meetings should be happening into a comment
- [x] fix the dates in meetup so that they match
- [x] clean up the content in each meetup
- [x] Setup links in CFA zoom for the Webinars
   - [x] Add panelists via the .csv to the invites
- [x] Add webinar registration link to comment below
- [x] add the link for the zoom to each meetup invite
- [x] Add all the webinar registrations to this Meetup URLs and Brigade Zoom Webinar URLs 2023 [spreadsheet](https://docs.google.com/spreadsheets/d/1RyczF7G8a-MIJECb3CWzjnBRuYdHpee9PLzUYJpqjPc/edit#gid=0)
- [x] Add 1Password vault for panelists 
- [x] Add the meeting registration links (webinar and second link) for onboarding for all dates
- [ ] Potentially, add the webinar passcode
   - [ ] 2023-01-03
   - [ ] 2023-01-16
   - [ ] 2023-01-31
   - [ ] 2023-02-13
   - [ ] 2023-02-28
   - [ ] 2023-03-13
   - [ ] 2023-03-28
   - [ ] 2023-04-10
   - [ ] 2023-04-25
   - [ ] 2023-05-08
   - [ ] 2023-05-23
   - [ ] 2023-06-12
   - [ ] 2023-06-27
   - [ ] 2023-07-10
   - [ ] 2023-07-25
   - [ ] 2023-08-14
   - [ ] 2023-08-29
   - [ ] 2023-09-11
   - [ ] 2023-09-26
   - [ ] 2023-10-16
   - [ ] 2023-10-24
   - [ ] 2023-11-06

### Resources/Instructions
- [Panelist list](https://docs.google.com/spreadsheets/d/1WT9ykFvpDv-P9ghyZ8YJ_V2CBBo3GqA3G5pK4t5a-uw/edit#gid=0)
- https://www.meetup.com/hackforla/events/
- [Onboarding: Meetup URLs and Brigade Zoom Webinar URLs 2023](https://docs.google.com/spreadsheets/d/1RyczF7G8a-MIJECb3CWzjnBRuYdHpee9PLzUYJpqjPc/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
# 2022 Meetup Dates
### November
- 2022-11-08
   - Meetup link:
   - Day of the week:
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_76vBaPfRRAebZ_9MbRgCWQ

# 2023 Meetup Dates
### Jan

- 2023-01-03
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfccbfb/
   - Day of the week: Tuesday
   - Zoom Registration link: https://codeforamerica.zoom.us/webinar/register/WN_oX8Avd3_Q_OApxNI67x4mw
- 2023-01-16
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfccbwb/
   - Day of the week: Monday
   - Zoom Registration link: https://codeforamerica.zoom.us/webinar/register/WN_HtNPxiqvRD65CudpMPqQtg
- 2023-01-31
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfccbpc/
   - Day of the week: Tuesday
   - Zoom Registration link: https://codeforamerica.zoom.us/webinar/register/WN_rqHBLQbPQeeH5mipczodJw

### Feb
- 2023-02-13
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfcdbsb/
   - Day of the week: Monday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_RCHvOK0sTCujanaQik6mYQ
- 2023-02-28
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfcdblc/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_-NJoKA9JRX6cFKHWar9JOw

### March
- 2023-03-13
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfcfbsb/
   - Day of the week: Monday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_2CyeaigSTBmmp2i7vI2Xaw
- 2023-03-28
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfcfblc/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_hRH4s8g-RyGZBfdshGD1uQ

### April
- 2023-04-10
   - Meetup link: https://www.meetup.com/hackforla/events/vfknzsyfcgbfb/
   - Day of the week: Monday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_Y6F4UZ-eTP61PdDaW0oSPQ
- 2023-04-25
   - Meetup link: https://www.meetup.com/hackforla/events/289631350/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_CcZ5eEzoShemZL3aakdZnQ

### May
- 2023-05-08
   - Meetup link: https://www.meetup.com/hackforla/events/289631371/
   - Day of the week: Monday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_aD43rUjuQEiYj3n8Lg8vlQ
- 2023-05-23
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfchbfc/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_TEg6dmw7SwiUB_6scomJUw

### June
- 2023-06-12
   - Meetup link: https://www.meetup.com/hackforla/events/vfknzsyfcjbqb/
   - Day of the week: Monday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_6tFL23K1QESNOHG1kDf_mg
- 2023-06-27
   - Meetup link: https://www.meetup.com/hackforla/events/289631884/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_ZXGQhe8fTTGB0RvJqPOmbw

### July
- 2023-07-10
   - Meetup link: https://www.meetup.com/hackforla/events/293863578/
   - Day of the week: Monday 
  ~~- Zoom Registration Link: https://codeforamerica.zoom.us/webinar/register/WN_MREeDsv2RnWardXh-ZEdqg~~
- 2023-07-25
   - Meetup link: https://www.meetup.com/hackforla/events/289632057/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_8CpEK8HQS-2vM4AVuQrA0A

### August
- 2022-08-14
   - Meetup link: https://www.meetup.com/hackforla/events/289631252/
   - Day of the week: Monday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_xbOyX-sBRCyyvCV633fqAA
- 2022-08-29
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfclbmc/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_L832s4IqRyKCw0qWPZzEGw

### September
- 2022-09-11
   - Meetup link: https://www.meetup.com/hackforla/events/vfknzsyfcmbgb/
   - Day of the week:  Monday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_9X_nx4JNSQmZdwrtRkWrxg
- 2022-09-26
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfcmbjc/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_JAfQ9HvTTTihT6vcdzlUaQ

### October
- 2022-10-16
   - Meetup link: https://www.meetup.com/hackforla/events/vfknzsyfcnbvb/
   - Day of the week: Monday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_tieimm_LREe2mLcEb-HiqA
- 2022-10-24
   - Meetup link: https://www.meetup.com/hackforla/events/pxkmhsyfcnbgc/
   - Day of the week: Tuesday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_kFn6C_OUQq2BL5L2h--IgQ

### November
- 2022-11-06
   - Meetup link: https://www.meetup.com/hackforla/events/289630916/
   - Day of the week: Monday
   - Zoom Registration Link: https://us06web.zoom.us/webinar/register/WN_woHBx4h-S2C_fBCO-hRnkA

**Comment by ExperimentsInHonesty** [comment]
@kcoronel I created a spreadsheet with all the info, because I needed it, so I would have an easy place to create and store the link for the second meeting (which can't be public) [Onboarding: Meetup URLs and Brigade Zoom Webinar URLs 2023](https://docs.google.com/spreadsheets/d/1RyczF7G8a-MIJECb3CWzjnBRuYdHpee9PLzUYJpqjPc/edit#gid=0)

Don't forget, we still need the rest of the year's worth of meetings to be created in the brigade zoom.

**Comment by kcoronel** [comment]
@ExperimentsInHonesty I need more clarity with this task "Setup links in CFA zoom for the Webinars", all other 
tasks have been completed, and we can close this issue on Saturday.

**Comment by ExperimentsInHonesty** [comment]
@kcoronel I finished adding all the links (except the webinar passcodes and slack links) to the meetings.

Next time we meet, let's test the passcodes to see if they are valuable.
I update the slack link before every meeting and update it in the 1password vaults

**Comment by kcoronel** [comment]
Tested links and Bonnie created a 1Password vault with Zoom information. Also created buffer meetings in the Code for America Zoom Brigade 1 so that no one schedules over our onboarding webinar (webinars don't show up on the meeting screen in Zoom)
