### ISSUE TITLE
Hack for LA 2022 Holiday Party Planning 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/admin#53]
### Overview
Planning Hack for LA's 2022 in-person holiday party. 
**Saturday, December 10, 2022**
**Time: 6:00 - 9:00 PM**
[MeetUp RSVP Link](https://www.meetup.com/hackforla/events/290125124/)

Virtual Holiday Party
**Saturday, December 14, 2022**
**Time: 6:00 - 9:00 PM**
Zoom link: 

### Action Items
Potential venues list: 
_venues below have a liberal option for reserving space i.e. no charge for reserving_ 
- [Arts District Brewing](https://www.artsdistrictbrewing.com/private-events) 12pm - 2am 
   -  under 21 okay until 7pm
   -  send email using [this form](https://www.artsdistrictbrewing.com/private-events)

No's: 
- [82 LA](https://www.eightytwo.la/) 2pm - 2am 
    - No RSVP needed, first come first serve 
 - [Home Bound Brew Haus](https://www.homeboundbrewhaus.com/) 12pm - 12am 
    - no RSVP needed, first come first serve 
    - might be too "adult"
- [Angel City Brewery](https://angelcitybrewery.com/) 12pm - 2am 
    - send email using [this form ](https://angelcitybrewery.com/contact/event-rental/)
- [Boomtown Brew](https://www.boomtownbrew.com/about/) 12pm - 2am 
    - no RSVP needed, first come first serve 

### Resources/Instructions
[Holiday Party Google folder ](https://drive.google.com/drive/folders/15qg3TNeGsI0iBt4wuEb1cbM9N3wuC0NQ?usp=sharing)

**Comment by kcoronel** [comment]
Draft Invite ![Holiday Party](https://user-images.githubusercontent.com/38144130/195994147-056bb65b-0657-4109-9e49-c811372e9c87.png)

**Comment by kcoronel** [comment]
Comments for image: 
Language updates 
Location 
Link to place

**Comment by ExperimentsInHonesty** [comment]
Sent the email
<html>
<body>
<span style="font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(35, 47, 77); font-family: avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif; text-align: center;">Hi Stephen,</span><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="text-align: center;"><font color="#232f4d" face="avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif"><br></font></div><div style="text-align: left;"><font color="#232f4d" face="avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif">Back in 2019 we had a get-together for our all volunteer organization, Hack for LA, and had a great time.</font></div><div style="text-align: left;"><font color="#232f4d" face="avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif"><br></font></div><div style="text-align: left;"><img src="https://mail.google.com/mail/u/0?ui=2&amp;ik=f370063ea3&amp;attid=0.1&amp;permmsgid=msg-a:r-6518616036300268000&amp;th=184d93a1d9595e3d&amp;view=fimg&amp;fur=ip&amp;sz=s0-l75-ft&amp;attbid=ANGjdJ_nRaP-CkY5wpee6-DxQpeN3aBDZFD0oZeYEdRe77OOruesudAdDUPDjouTq9Zk04GgfA09NF-mXDd6UjCgMtXBXNYOWjSgWfX4PCsuhowNQQ7Hb2LGm2AcpEQ&amp;disp=emb&amp;realattid=ii_lb89aedj0" alt="image.png" width="168" height="126" data-image-whitelisted="" class="CToWUd a6T" data-bit="iit" tabindex="0" style="cursor: pointer; outline: 0px; margin-right: 0px;"><br></div><div style="text-align: left;"><font color="#232f4d" face="avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif">We know you don't reserve tables on weekends, but thought we should give you a heads-up that we are going to be coming on Saturday the 10th and so far 20 people have Rsvp'd</font></div><div><span style="color: rgb(35, 47, 77); font-family: avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif; text-align: center;"><br></span></div><div><span style="color: rgb(35, 47, 77); font-family: avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif; text-align: center;">Do you want us to let you know when the date gets closer how many people have rsvp'd?</span></div><div><span style="color: rgb(35, 47, 77); font-family: avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif; text-align: center;"><br></span></div><div><span style="color: rgb(35, 47, 77); font-family: avenir-lt-w01_35-light1475496, avenir-lt-w05_35-light, sans-serif; text-align: center;">Best,<br><br></span></div><div><div dir="ltr" data-smartmail="gmail_signature"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div style="min-width: 600px; width: 755.333px;">

  | Bonnie WolfeBrigade Captain, Executive Director, Hack for LA310-740-1161Hack for LA is an official brigade of Code for America
-- | --


</div></div></div></div></div></div></div></div></div></div></div></div>
</body>
</html>Hi Stephen,

Back in 2019 we had a get-together for our all volunteer organization, Hack for LA, and had a great time.

image.png
We know you don't reserve tables on weekends, but thought we should give you a heads-up that we are going to be coming on Saturday the 10th and so far 20 people have Rsvp'd

Do you want us to let you know when the date gets closer how many people have rsvp'd?

Best,

photo-logo	
Bonnie Wolfe
Brigade Captain, Executive Director, [Hack for LA](https://www.hackforla.org/)
310-740-1161
Hack for LA is an official brigade of Code for America

**Comment by ExperimentsInHonesty** [comment]
We posted the event on Meetup on https://www.meetup.com/hackforla/events/290125124/

**Comment by ExperimentsInHonesty** [comment]
Virtual party details
Date: 2022-12-14
Time: 6-9 pm pst
Zoom 4 
Zoom Registration
Zoom Authentication
Title: Hack for LA Holiday Party 🎉 VIRTUAL
Description:

Slack message:

**Comment by kcoronel** [comment]
Closing this issue as holiday party planning has been completed.

**Comment by ExperimentsInHonesty** [comment]
Stephen Dorame is our contact at Arts District
