### ISSUE TITLE
Calendar: Projects calendar share with org

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#55]
### Overview
We need to make sure all the projects' calendars are shared with hfla-calendar@hackforla.org so that we can be able to see or change any project's invites

### Action Items
- [x] log into email account
- [x] go to calendar
- [x] share calendar with hfla-calendar@hackforla.org
- [x] make sure none of the existing invites have hfla-calendar@hackforla.org as an invitee
- [x] update spreadsheet

### Resources/Instructions
- [CAL: Active Project List](https://docs.google.com/spreadsheets/d/1ROrkkvvRXHlaTw18V3Ts5tml9KPUm4DasAMyeKgCTR4/edit)
- [Zoom sheet](https://docs.google.com/spreadsheets/d/15P3MYyNQ7Xn0pqdrTynDDipjrLl5LCN9xHVLhk9SWa8/edit#gid=0&fvid=1431871656)
- [Zoom Account audit](https://docs.google.com/spreadsheets/d/1KKkULDX3g4Ou7qN3i7B9JJxs7P4ubyc9MUkAV7C56yw/edit#gid=971333725)

**Comment by Rabia2219** [comment]
Dependency removed and completed.
