### ISSUE TITLE
Hack for LA 2023 Holiday Party

### ISSUE THREAD

**Issue by kcoronel** [hackforla/admin#78]
### Overview
Planning Hack for LA's 2023 in-person holiday party. 
**Saturday, December 9, 2023**
**Time: 6:00 - 8:00 PM**
[MeetUp RSVP Link]()
**Location:**[Angel City Brewery](https://angelcitybrewery.com/) 12pm - 2am - due to size
    - send email using [this form ](https://angelcitybrewery.com/contact/event-rental/)

### Action Items
- [ ] Message venue to reserve space 
- [ ] Research local LA civic tech organizations 
- [ ] Create draft email to send to local civic tech organizations 
- [ ] Send email to local civic tech organizations 
- [ ] Create flyer for holiday party 
- [ ] Create event in MeetUp for the holiday party 
- [ ] Promote holiday party/RSVP on #general channel Slack 

Potential venues list: 
_venues below have a liberal option for reserving space i.e. no charge for reserving_ 
- [Arts District Brewing](https://www.artsdistrictbrewing.com/private-events) 12pm - 2am 
   -  under 21 okay until 7pm
   -  send email using [this form](https://www.artsdistrictbrewing.com/private-events)
- [82 LA](https://www.eightytwo.la/) 2pm - 2am 
    - No RSVP needed, first come first serve 
 - [Home Bound Brew Haus](https://www.homeboundbrewhaus.com/) 12pm - 12am 
    - no RSVP needed, first come first serve 
    - might be too "adult"
- [Angel City Brewery](https://angelcitybrewery.com/) 12pm - 2am 
    - send email using [this form ](https://angelcitybrewery.com/contact/event-rental/)
- [Boomtown Brew](https://www.boomtownbrew.com/about/) 12pm - 2am 
    - no RSVP needed, first come first serve 

### Resources/Instructions
[Holiday Party Google folder ](https://drive.google.com/drive/folders/1KdMsDEeK6vLoXd04gKf4CVtifZv9XS15?usp=drive_link)
Last Year's Issue: #53

**Comment by kcoronel** [comment]
Sent an email to Angel City Brewery using [this form](https://angelcitybrewery.com/contact/event-rental/).

**Comment by kcoronel** [comment]
@kcoronel to create Meet-up and graphic leave in draft

**Comment by kcoronel** [comment]
@bonniewolfe [here is a Canva link](https://www.canva.com/design/DAFPHvbqIUg/ygILvqHUDQfGgUeOQUVTww/edit?utm_content=DAFPHvbqIUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) to the holiday invite. I used the graphic to create the Meet-Up event which is now in drafts.

**Comment by kcoronel** [comment]
@kcoronel to email Jessica - 5-10min - give Bonnie's number 

annual event for every civic tech volunteer in LA to do their holiday party at once. Working towards same goal, organize a day a year for holiday party together for cross functional collaboration

**Comment by kcoronel** [comment]
Bonnie created a Slack 
Party details
:round_pushpin:Address: 350 S Grand Ave, Los Angeles, CA ([map](https://www.google.com/maps/place/350+S+Grand+Ave,+Los+Angeles,+CA+90071/@34.0516856,-118.2566177,17z/data=!3m1!4b1!4m6!3m5!1s0x80c2c77b237eda85:0x6b1cfd80b88665c6!8m2!3d34.0516813!4d-118.2517468!16s%2Fg%2F11sqv726k7?entry=ttu)), indoors in a room off the lobby (floorplan in a separate post)
:alarm_clock: Time: 8-9  6-8 pm (see thread for more details including after party info)
:nerd_face: Dress code: Ugly holiday sweaters, or business casual
:dango: Food: We will be providing sandwich trays, veggies, cookies, fruit, etc.  And non alcoholic drinks.
:tada: Activities:
[@Judson](https://hackforla.slack.com/team/U9NFW84QK)
 is brining games for us to play (more details in a separate post)
Ugly sweater contest (more details in a separate post)
TBD
:car: Parking: There is $15 flat rate parking after 5:01 pm
Q&A
How Can I help?
We could use party committee members to organize the sweater contest
We could have a raffle to raise money but we don't have any prizes.  Someone suggested a white elephant raffle with the prizes being gathered from volunteers who want to donate something, but I don't have time to organize this...
setup
cleanup
Should I bring my laptop?
I don't think so, its a party!!  But if you want to, its ok.
Help organize some of the carpools.  We have people coming from as far away as San Diego, Irvine, Redondo Beach, Riverside, etc.
Will there be an outdoor area?
We are right on the plaza, so theoretically people could hang out, outside, but we are not planning any activities or tables/chairs out there.
(edited)





5 replies
Last reply 2 months agoView thread





Pinned by 
Bonnie


Bonnie
  [11:41 AM](https://hackforla.slack.com/archives/C069P36JBGQ/p1701978086236769)
After party details
Its a long way to come for just 2 hours.  And more people want to come than we potentially have space for.  I stopped sending invitations on LinkedIn to members when we crossed over the space limit, but I easily could invite another hundred people.  Sooo... after the main party happens, we can slide on over to https://angelcitybrewery.com/ if anyone is game.  If you plan to take a train to the party then we can probably hook you up with a ride to the after party. (edited) 
:+1:
3

[11:43](https://hackforla.slack.com/archives/C069P36JBGQ/p1701978189832759)
Floorplan for the event space : https://my.matterport.com/show/?m=P1FLsv6Aimt



https://photos.app.goo.gl/Wx4zaCYGxtYxt58P6

**Comment by kcoronel** [comment]
https://github.com/civictechstructure/party/issues/4

**Comment by kcoronel** [comment]
Closing as this passed.

**Comment by Rabia2219** [comment]
[Holiday Party Photos](https://photos.google.com/share/AF1QipMU84pqgJ7PNk0KFStQ93-izezrqJYm6l86k45p_fqzK00vd4t79SOumFYPfRDuWA?pli=1&key=NEJnN2w3OVBRNEczdEZCZjVYd01kdldxeHdWWFZB)
