### ISSUE TITLE
Summer 2024 Party

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/admin#82]
### Overview
This issue will help us coordinate planning for Hack for LA's Summer Picnic happening on July 13, 2024 at Cheviot Hills Recreation Area. 

### Action Items
- [x] Secure location and make deposit 
- [x] Create graphic for invites 
- [x] Create language for Slack posting 
- [x] Create a form for what people are bringing
   - [x] spreadsheet for what people will bring to picnic will show
      - category
      - item description
      - number of servings
      - Ingredients (for allergic purposes)
- [x] Create LinkedIn Invite Meeting

### Resources/Instructions
- [2024 Summer Party Folder](https://drive.google.com/drive/folders/1yT9EXR-d81qjwc2H9_4RA_thy_PgCp9S?usp=drive_link)
- Contribution Form 
   - [view](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/edit)
   - [edit](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/edit)
   - [responses in form](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/edit#responses)
   - [responses in sheets (public)](https://docs.google.com/spreadsheets/d/1uwrrc3SCPRKSxB3qJMysBtJTK0tJWgzk0BehrZP9IrY/edit?resourcekey=&gid=55212534#gid=55212534)
   - preview version of responses: [see what other people are bringing](https://docs.google.com/spreadsheets/d/1uwrrc3SCPRKSxB3qJMysBtJTK0tJWgzk0BehrZP9IrY/preview)
- WIKI Page: https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Directions,-Parking-info-and-Pictures

#### View the picnic area
<details><summary>Image of picnic area</summary>

![image](https://github.com/hackforla/admin/assets/37763229/18551d56-5cc7-4dda-acf4-59017fe89f80)
</details> 

[link to view the picnic area](https://www.google.com/maps/@34.0455848,-118.4123468,3a,75y,115.8h,90t/data=!3m7!1e1!3m5!1sSbq6gzt7wuK5f3EgPg-nZA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DSbq6gzt7wuK5f3EgPg-nZA%26cb_client%3Dmaps_sv.share%26w%3D900%26h%3D600%26yaw%3D115.80002874610106%26pitch%3D0%26thumbfov%3D90!7i16384!8i8192?coh=205410&entry=ttu)

#### Maps
- Address of event: 2551 Motor Ave., Los Angeles, CA 90064
- Cartoon map from park service https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/map.pdf
- [directions to parking area next to picnic](https://www.google.com/maps/dir//Parking+lot,+2459+Motor+Ave,+Los+Angeles,+CA+90064/@34.0454435,-118.4125289,18z/data=!4m9!4m8!1m0!1m5!1m1!1s0x80c2bbc1ddaf5edf:0xf585812f0d29eb59!2m2!1d-118.4122027!2d34.0457214!3e0?entry=ttu) - When this lot is full, use the main lot.
- [directions to overflow parking in the main lot](https://www.google.com/maps/place/2551+Motor+Ave+Parking/@34.0471309,-118.4086059,17z/data=!4m6!3m5!1s0x80c2bbc2769b2d45:0x9f035fa59a4e957d!8m2!3d34.04679!4d-118.4084493!16s%2Fg%2F11f3sfhh9c?entry=ttu) - This is the main parking for the park. It's a [5-min walk between the main parking lot and the picnic area](https://www.google.com/maps/dir/2551+Motor+Ave+Parking,+Parking+lot,+2551+Motor+Ave,+Los+Angeles,+CA+90064/'34.0454435,-118.4125289'/@34.0467563,-118.4117923,18z/data=!3m1!4b1!4m12!4m11!1m5!1m1!1s0x80c2bbc2769b2d45:0x9f035fa59a4e957d!2m2!1d-118.4084493!2d34.04679!1m3!2m2!1d-118.4125289!2d34.0454435!3e2?entry=ttu)

#### graphics for invites/forms
- LinkedIn
  - linkedin Event 'Banner' Size: 16:9 ratio, preferably 1600 x 900 pixels. [Article with banner size advice](https://www.linkedin.com/pulse/linkedin-image-size-guide-julie-thomas-tftwc)
      <details><summary>LinkedIn Image</summary>

       [Where to Edit](https://www.canva.com/design/DAGHPFhKk9M/U5YiVbg4z2m3bgAVA2OlPw/edit?utm_content=DAGHPFhKk9M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

      Use for posting:
       ![Hack for LA Picnic Graphic - LinkedIn](https://github.com/hackforla/admin/assets/38144130/c7e8ed85-ef3c-475a-b10e-4e4add88f4b2)
      </details> 

- Google Forms
  - image needed for google form banner 1600x400
       <details><summary>Google Forms Image</summary>

       [Where to edit](https://www.canva.com/design/DAGHS2Je3Lw/OBY7z6tioXRFA-OfnJ1VEw/edit?utm_content=DAGHS2Je3Lw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

       ![Header for Google Forms - Hack for LA Picnic](https://github.com/hackforla/admin/assets/38144130/981010d0-95fe-4224-a6ae-b4acdb930943)
      </details> 
- Other
[Alphabetical list of cities for California and Southern California](https://www.landsmart.com/index.php?option=com_content&view=article&id=161&Itemid=113)
- [Cheviot Hills](https://www.laparks.org/reccenter/cheviot-hills)
- [Info about reserving PDF](https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/picnic-areas-info-and-agreement-24.pdf)
   - Applications accepted for the full year starting January 2nd
   - email to reserve on the above document
- [Permit Application](https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/permit-application-agreement-24.pdf)

**Comment by Rabia2219** [comment]
- start looking at parks available for booking in the Playa Vista area
  - https://playavista.com/active-outdoors/parks-rec/
  - https://playavista.com/contact-us/

**Comment by Rabia2219** [comment]
- July 13th and 20th: 
  - Fountain Park, no restrooms, only grass area, $350/4hrs, $750 deposit
- July 6th and 27th,
   - Concert Park, restrooms, $500/4hrs, $750 deposit

email: maricela.sandozal@seabreezemgmt.com

**Comment by Rabia2219** [comment]
#### Notes for draft proposal

- determination letter and link (slack)
- bathrooms
- beach chairs, picnic blanket, lawn games (fast four, corn hole, frisbee, ring toss, giant Jenga etc.)
- no vendors
- potluck, will be taken back
- 4 folding tables for food (all precooked)
- invite only to HfLA members (security)
- parking (car pool)
- alcohol free
- look up insurance from last party issue
- premade badges
- look at draft and suggest security

**Comment by Rabia2219** [comment]
#### Beach Option

- https://beaches.lacounty.gov/dockweiler-beach-fire-pits/

**Comment by ExperimentsInHonesty** [comment]
We ended up at Cheviot Hills Recreation Area 
[Facility Rental Information Picnic Areas map]

**Comment by ExperimentsInHonesty** [comment]
Form will ask:
Name
Email
Slack
Phone
category
item description
number of servings
Ingredients (for allergic purposes)

**Comment by ExperimentsInHonesty** [comment]
graphic for invite
linkedin Event 'Banner' Size: 16:9 ratio, preferably 1600 x 900 pixels.Mar 5, 2024 https://www.linkedin.com/pulse/linkedin-image-size-guide-julie-thomas-tftwc

**Comment by kcoronel** [comment]
https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/map.pdf

**Comment by Rabia2219** [comment]
#### Slack Post Draft

**Comment by Rabia2219** [comment]
#### Meetup Post Draft

**Comment by Rabia2219** [comment]
#### LinkedIn Post Draft

**Comment by Rabia2219** [comment]
#### Slack Post Draft
:mega: Hey Everyone! We're excited to announce our upcoming Summer Party!

:tada: Join us for a fun day at the park, filled with great food, drinks, games, and awesome company. Friends and families are welcome, so feel free to bring them along!

:date: Date: July 13th, 2024
:clock3: Time: 12 PM PST
:round_pushpin: Location: Cheviot Hills Recreation Area, Los Angeles

:white_check_mark: Find all the details on Meetup and RSVP now!

:eyes: Looking forward to seeing you there!

**Comment by Rabia2219** [comment]
#### LinkedIn Post Draft

**Comment by kcoronel** [comment]
[1st Draft of Graphic](https://www.canva.com/design/DAGHPFhKk9M/U5YiVbg4z2m3bgAVA2OlPw/edit?utm_content=DAGHPFhKk9M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by ExperimentsInHonesty** [comment]
image needed for google form banner 

1600x400

**Comment by kcoronel** [comment]
[Where to edit](https://www.canva.com/design/DAGHS2Je3Lw/OBY7z6tioXRFA-OfnJ1VEw/edit?utm_content=DAGHS2Je3Lw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

![Header for Google Forms - Hack for LA Picnic](https://github.com/hackforla/admin/assets/38144130/981010d0-95fe-4224-a6ae-b4acdb930943)

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/hackforla/admin/assets/37763229/18551d56-5cc7-4dda-acf4-59017fe89f80)

**Comment by ExperimentsInHonesty** [comment]
https://linkedin.com/in/bonnieawolfe

**Comment by Rabia2219** [comment]
- We need a privacy policy on how we will use the invitees information

**Comment by Rabia2219** [comment]
#### Invite Post Draft

**🌞 Hack for LA Summer Potluck Party! 🌞**

[Image with date, time, location]

Join us for a fun-filled summer potluck party in the park! Hack for LA members, friends, families, and well-behaved pets (dogs must be leashed) are all welcome to attend. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

**What to Bring:**

- Food & Drinks: Please bring your favorite dish and beverages to share.
- Games & Activities: Feel free to bring any games or activities you'd like to enjoy with others.

**Contribution Form:**

To help us organize the event better, please fill out the [contribution form](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/view) with the items you plan to bring. This will help avoid duplicates and ensure we have a variety of food and drinks.

**Not a Member Yet?**

Our party is only open to members.  If you are interested in volunteering with us, we encourage you to attend our [last onboarding session in June (Tuesday, June 18th 2024](https://www.meetup.com/hackforla/events/298147579/)), so you can join our community and attend the party. 

Come out, have fun, and connect with fellow Hack for LA members. We look forward to seeing you there!

**Comment by ExperimentsInHonesty** [comment]
```
@channel

**🌞 Hack for LA Summer Potluck Picnic! 🌞**

Join us for a fun-filled summer potluck picnic in the park! Hack for LA members, friends, families, and well-behaved pets are all welcome to attend (dogs must be leashed)*. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

**Mark Your Calendar**

:date: Date: July 13th, 2024
:clock3: Time: 12 PM - 3 PM PST
:round_pushpin: Location: Cheviot Hills Recreation Area, Los Angeles (Picnic Area 2)

**What to Bring:**

- Food & Drinks*: Please bring your favorite dish and beverages to share.
- Games & Activities*: Feel free to bring any games or activities you'd like to enjoy with others.

**Contribution Form:**

To help us organize the event better, please fill out the [contribution form](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/viewform) with the items you plan to bring. This will help avoid duplicates and ensure we have a variety of food and drinks.

**Picnic Area Details**
[Maps, pictures and other details](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Directions,-Parking-info-and-Pictures)

**Let Us Know You're Coming**
Come out, have fun, and connect with fellow Hack for LA members. We look forward to seeing you there!

✅ [RSVP on meetup now](https://www.meetup.com/hackforla/events/301856645/)! 

*[Cheviot Hills Recreation Center Regulations](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Regulations)

**Comment by kcoronel** [comment]
Learnings: don't add a lot of information to LinkedIn invite and limit to one link so that we can navigate people to the MeetUp RSVP page. At Admin meeting we have a discrepancy between folks who RSVP'd in LinkedIn and those who have RSVP'd on Meet Up.

**Comment by senakim18** [comment]
9/12: Bonnie (from [team@civictechstructure.org](mailto:team@civictechstructure.org)) sent thank you & follow-up emails to attendees of 2024 Summer Potluck who donated & didn't donate (respectively). Email templates & notes can be found [here](https://drive.google.com/drive/folders/1jWwFAgFLNPz3blFW3IxkO8Nsd3CpH2m2).

11/7: Bonnie (from [team@civictechstructure.org](mailto:team@civictechstructure.org)) sent thank you emails to Shienny & Saumil who donated after receiving the email. Bonnie also sent a thank you LinkedIn message to Gerald Yao.
