### ISSUE TITLE
In-fill Board: Karen

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/admin#9]
### Overview
We need to document what happened between Bonnie and admin team in last week's brain dumps.

### Action Items
- [x] Reach out to Karen who met with Bonnie at Tuesday, June 22⋅5:30 – 6:00pm and find out what process they were modeling
- [ ] Ask Karen to upload the files Bonnie sent her to the Google Drive
- [x] Assign Karen the related issue

### Resources/Instructions
- [Files from recording currently hosted on Zoom](https://us02web.zoom.us/rec/share/_H7x_XuWmiYaCRdZWFjRYWqxEJ6YMiRNYkqZAcK2_1qh0qmX8R9D2D4qmOju4ijR.MkY9pDBKxzTu8DM2)
- [Recordings Folder](https://drive.google.com/drive/folders/1i_mjlTp0tNfUiXeXN4YmbbuJg6iF-hPz)

**Comment by kcoronel** [comment]
@glenflorendo thanks! Can you tell me what google drive is best. Thank you!

**Comment by glenflorendo** [comment]
> @glenflorendo thanks! Can you tell me what google drive is best. I am modeling the 1Password Guide. Thank you!

Hi @kcoronel ! Could you please upload to the [Recordings Folder](https://drive.google.com/drive/folders/1i_mjlTp0tNfUiXeXN4YmbbuJg6iF-hPz)? Thanks!

**Comment by glenflorendo** [comment]
> > @glenflorendo thanks! Can you tell me what google drive is best. I am modeling the 1Password Guide. Thank you!
> 
> Hi @kcoronel ! Could you please upload to the [Recordings Folder](https://drive.google.com/drive/folders/1i_mjlTp0tNfUiXeXN4YmbbuJg6iF-hPz)? Thanks!

@kcoronel: Bonnie shared the recordings files from your meeting with her with me. I uploaded them to the Google Drive. Could you confirm that it's complete? Thanks!
